# See #REF_DEV_VERDACCIO
storage: /verdaccio/storage
middlewares:
  audit:
    enabled: true
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@wbtdevlocal/*":
    access: $anonymous
    publish: $anonymous
    unpublish: $anonymous
  "@*/*":
    access: $anonymous
    publish: $authenticated
    proxy: npmjs
  "**":
    access: $anonymous
    publish: $authenticated
    proxy: npmjs
web: 
  enable: true  
  title: WBT - Verdaccio
  primary_color: "#3794EB"
  darkMode: true