# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/
# Remember:
#   - 'context' is relative to the directory of this yaml file. Or, a git URL.
#   - 'container_name' can't be used with scaling

services:
  # All source code is in one container
  devcode:
    container_name: wbt-devcode
    build:
      context: ../../ # host machine's top workspace folder
      dockerfile: ./utility/local-dev/local-dev.Dockerfile
      args:
        - ARG_VERDACCIO_PORT=4873
    environment:
      - NODE_ENV=dev
      - PORT=8000
      - WBT_SEQ_URL=http://wbt-dev-seq:5341
      - VERDACCIO_PORT=4873
    tty: true # Keep this on. Otherwise, it will end immediately.
    volumes:
      # Match up top-level directory to 'src'.
      # Everything under that, including .git and .vscode, are in the container.
      - ../../:/usr/src
      # List the node_modules below so they are saved in volumes, not on the host.
      - volume-wbt-devcode-modules-assets:/usr/src/projects/assets/node_modules
      - volume-wbt-devcode-modules-build:/usr/src/utility/build/node_modules
      - volume-wbt-devcode-modules-client:/usr/src/projects/client/node_modules
      - volume-wbt-devcode-modules-iso:/usr/src/projects/iso/node_modules
      - volume-wbt-devcode-modules-server:/usr/src/projects/server/node_modules
      - volume-wbt-devcode-modules-server-http:/usr/src/projects/server-http/node_modules
    ports:
      - "8093:8000" # Server
      - "8094:58888" # Cosmos
    depends_on:
      - seq
  verdaccio:
    container_name: wbt-dev-verdaccio
    # See #REF_DEV_VERDACCIO
    # https://verdaccio.org/docs/docker
    image: verdaccio/verdaccio
    volumes:
      - ./verdaccio-config:/verdaccio/conf
      - volume-wbt-dev-verdaccio:/verdaccio/storage
    ports:
      - "8095:4873" # Verdaccio UI
  seq:
    container_name: wbt-dev-seq
    # https://docs.datalust.co/docs/getting-started-with-docker
    image: datalust/seq:latest
    volumes:
      - volume-wbt-dev-seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8091:80"
  nginx:
    container_name: wbt-dev-nginx
    # https://hub.docker.com/_/nginx
    image: nginx:1.19.6-alpine
    environment:
      - WBT_NGINX_SERVER_LISTEN=80
      - WBT_DEVCODE_SERVER_PORT=8093
      - WBT_NGINX_COSMOS_LISTEN=81
      - WBT_DEVCODE_COSMOS_PORT=5000
    volumes:
      # Set configuration for reverse proxy. (See https://hub.docker.com/_/nginx)
      - ./nginx-templates:/etc/nginx/templates
      # Static Files
      # Note! don't nest directories, as it messes up bindings when directories get deleted.
      - ../../../projects/client/dist:/usr/share/nginx/wbt/dist
      - ../../../projects/assets/dist-icons:/usr/share/nginx/wbt/icons
    ports:
      - "8090:80" # App
      - "8092:81" # Cosmos
    depends_on:
      - devcode
volumes:
  # Each node_modules also needs a volume for persistent storage
  volume-wbt-devcode-modules-assets:
  volume-wbt-devcode-modules-build:
  volume-wbt-devcode-modules-client:
  volume-wbt-devcode-modules-iso:
  volume-wbt-devcode-modules-server:
  volume-wbt-devcode-modules-server-http:
  volume-wbt-dev-seq:
  volume-wbt-dev-verdaccio:
